# Generated by Django 4.2.2 on 2023-11-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_remove_quiz_created_remove_quiz_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=5, help_text="Time limit in minutes."
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(help_text="Add a description to your quiz."),
        ),
    ]
