# Generated by Django 4.2.2 on 2023-11-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="quiz", name="datecompleted",),
    ]
